name: Deploy Flutter TG Mini App

on:
  push:
    branches: [ main ] # Триггер на пуш в main ветку

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Установка Flutter
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.4' # Укажите вашу версию

    # Установка зависимостей
    - run: flutter pub get

    # Сборка web версии
    - run: flutter build web --release
    
    - name: Debug Connection
      run: |
        echo "Host: ${{ secrets.VPS_HOST }}"
        echo "User: ${{ secrets.VPS_USER }}"
        echo "Port: ${{ secrets.VPS_PORT || '22' }}"
        echo "Password length: ${#VPS_PASSWORD}"  # Проверка длины пароля

    # Деплой на VPS через SSH
    - name: Deploy to VPS
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        source: "build/web/"
        target: "/var/www/tg-mini-app/" # Путь на сервере
